// Code generated by goctl. DO NOT EDIT!
// Source: pair.proto

package pair

import (
	"context"

	"github.com/acger/pair-svc/pb/pair"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ELeListRsp  = pair.ELeListRsp
	EleListReq  = pair.EleListReq
	ElePairReq  = pair.ElePairReq
	EleSaveReq  = pair.EleSaveReq
	EleViewReq  = pair.EleViewReq
	EleViewRsp  = pair.EleViewRsp
	Element     = pair.Element
	Response    = pair.Response
	UserElement = pair.UserElement

	Pair interface {
		ElementSave(ctx context.Context, in *EleSaveReq, opts ...grpc.CallOption) (*Response, error)
		ElementView(ctx context.Context, in *EleViewReq, opts ...grpc.CallOption) (*EleViewRsp, error)
		ElementList(ctx context.Context, in *EleListReq, opts ...grpc.CallOption) (*ELeListRsp, error)
		ElementPair(ctx context.Context, in *ElePairReq, opts ...grpc.CallOption) (*ELeListRsp, error)
	}

	defaultPair struct {
		cli zrpc.Client
	}
)

func NewPair(cli zrpc.Client) Pair {
	return &defaultPair{
		cli: cli,
	}
}

func (m *defaultPair) ElementSave(ctx context.Context, in *EleSaveReq, opts ...grpc.CallOption) (*Response, error) {
	client := pair.NewPairClient(m.cli.Conn())
	return client.ElementSave(ctx, in, opts...)
}

func (m *defaultPair) ElementView(ctx context.Context, in *EleViewReq, opts ...grpc.CallOption) (*EleViewRsp, error) {
	client := pair.NewPairClient(m.cli.Conn())
	return client.ElementView(ctx, in, opts...)
}

func (m *defaultPair) ElementList(ctx context.Context, in *EleListReq, opts ...grpc.CallOption) (*ELeListRsp, error) {
	client := pair.NewPairClient(m.cli.Conn())
	return client.ElementList(ctx, in, opts...)
}

func (m *defaultPair) ElementPair(ctx context.Context, in *ElePairReq, opts ...grpc.CallOption) (*ELeListRsp, error) {
	client := pair.NewPairClient(m.cli.Conn())
	return client.ElementPair(ctx, in, opts...)
}
