Name: pair.rpc
ListenOn: 0.0.0.0:60002
Etcd:
  Hosts:
    - dev.ll:2379
  Key: pair.rpc
Datasource: root:123456@tcp(dev.ll:3306)/fireflyPair?charset=utf8mb4&parseTime=True&loc=Local
Cache:
  - Host: dev.ll:6379
UserSvc:
  Etcd:
    Hosts:
      - dev.ll:2379
    Key: user.rpc
Log:
  ServiceName: "pair-svc"
  Mode: "file"
  Path: "/var/log/filebeat/pair-svc"
  Level: "error"