// Code generated by goctl. DO NOT EDIT!
// Source: pair.proto

//go:generate mockgen -destination ./pair_mock.go -package pairclient -source $GOFILE

package pairclient

import (
	"context"

	"github.com/acger/pair-svc/pair"

	"github.com/tal-tech/go-zero/zrpc"
)

type (
	EleViewRsp  = pair.EleViewRsp
	EleSaveReq  = pair.EleSaveReq
	UserElement = pair.UserElement
	Element     = pair.Element
	ELeListRsp  = pair.ELeListRsp
	EleListReq  = pair.EleListReq
	ElePairReq  = pair.ElePairReq
	EleViewReq  = pair.EleViewReq
	Response    = pair.Response

	Pair interface {
		ElementSave(ctx context.Context, in *EleSaveReq) (*Response, error)
		ElementView(ctx context.Context, in *EleViewReq) (*EleViewRsp, error)
		ElementList(ctx context.Context, in *EleListReq) (*ELeListRsp, error)
		ElementPair(ctx context.Context, in *ElePairReq) (*ELeListRsp, error)
	}

	defaultPair struct {
		cli zrpc.Client
	}
)

func NewPair(cli zrpc.Client) Pair {
	return &defaultPair{
		cli: cli,
	}
}

func (m *defaultPair) ElementSave(ctx context.Context, in *EleSaveReq) (*Response, error) {
	client := pair.NewPairClient(m.cli.Conn())
	return client.ElementSave(ctx, in)
}

func (m *defaultPair) ElementView(ctx context.Context, in *EleViewReq) (*EleViewRsp, error) {
	client := pair.NewPairClient(m.cli.Conn())
	return client.ElementView(ctx, in)
}

func (m *defaultPair) ElementList(ctx context.Context, in *EleListReq) (*ELeListRsp, error) {
	client := pair.NewPairClient(m.cli.Conn())
	return client.ElementList(ctx, in)
}

func (m *defaultPair) ElementPair(ctx context.Context, in *ElePairReq) (*ELeListRsp, error) {
	client := pair.NewPairClient(m.cli.Conn())
	return client.ElementPair(ctx, in)
}
